# Generated by Django 5.2 on 2025-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_event_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
