# Generated by Django 5.2 on 2025-04-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_event_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
