# Generated by Django 5.2 on 2025-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_event_quantity_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(max_length=255),
        ),
    ]
